export const PROJECTS = [
    {
        id: "01",
        title: "Meronatic PRO",
        description: "UAE Corporate Services & Business Support platform designed for seamless business operations.",
        category: "Corporate Services",
        year: "2026",
        role: "Design & Development",
        image: "/meronatic-pro.png",
        link: "https://pro.meronatic.com/",
    },
    {
        id: "02",
        title: "VNTNR",
        description: "Mobile application design focused on intuitive user experience and modern aesthetics.",
        category: "App Design",
        year: "2023",
        role: "UI/UX Design",
        image: "https://framerusercontent.com/images/QhPkJGJBXS8kPS7IhPj7ZBGZpII.png",
    },
    {
        id: "03",
        title: "Aeorim",
        description: "Art direction and digital presence for a luxury fashion brand.",
        category: "Art Direction",
        year: "2023",
        role: "Creative Direction",
        image: "https://framerusercontent.com/images/yOPV9nZRSJXmNPqyeWfZSThWAc.png",
    },
];
